version: '3'
services:
  web:
    container_name: funpay-nginx
    image: nginx
    restart: always
    volumes:
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
  php:
    container_name: funpay-php
    build: docker/conf/php
    restart: always
    command: bash -c "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && /usr/local/sbin/php-fpm"
    volumes:
      - ./public:/var/www/html
      - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
  db:
    container_name: funpay-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password